// JiraFileSystem+ServerURL.m
// Implements the FSServerURLUnaryOperations informal protocol (private FSKit API).
// This protocol is required for URL-based (jira://) filesystem mounting via FSClient.
//
// Protocol methods (from ObjC runtime):
//   - startOpeningSessionWithTask:url:options:error:  -> FSServerSessionInfoTask*
//   - startServerInfoFetchWithTask:url:options:error: -> FSServerInfoTask*
//   - parseURL:replyHandler:
//   - composeURL:replyHandler:
//   - closeSession:replyHandler:

#import <Foundation/Foundation.h>
#import <FSKit/FSKit.h>
#import <objc/runtime.h>

// Private FSKit types — forward declarations only; we interact via id.
@interface FSServerURLParameters : NSObject
@property (nonatomic, copy) NSString *scheme;
@property (nonatomic, copy) NSString *host;
@property (nonatomic, copy) NSString *user;
@property (nonatomic, copy) NSString *password;
@property (nonatomic, copy) NSString *path;
@property (nonatomic, copy) NSNumber *port;
@property (nonatomic, copy) NSDictionary *options;
@end

@interface FSServerInfoTask : FSTask
- (void)didCompleteWithServerInfo:(id)info;
@end

@interface FSServerSessionInfoTask : FSTask
- (void)didCompleteWithServerSessionInfo:(id)info;
@end

// ---------------------------------------------------------------------------
// JiraFileSystem category — FSServerURLUnaryOperations conformance
// ---------------------------------------------------------------------------

// Forward-declare the Swift-generated class so ObjC can see it.
// The actual @implementation is generated by the Swift compiler.
@interface JiraFileSystem : FSUnaryFileSystem
@end

@interface JiraFileSystem (ServerURL)

/// Called by fskitd to establish a session to the server.
/// Return an FSServerSessionInfoTask; call -didCompleteWithServerSessionInfo: when done.
- (id)startOpeningSessionWithTask:(FSTask *)task
                              url:(NSURL *)url
                          options:(NSDictionary *)options
                            error:(NSError **)error;

/// Called by fskitd to fetch server information (display name, etc.).
/// Return an FSServerInfoTask; call -didCompleteWithServerInfo: when done.
- (id)startServerInfoFetchWithTask:(FSTask *)task
                               url:(NSURL *)url
                           options:(NSDictionary *)options
                             error:(NSError **)error;

/// Parse a URL into FSServerURLParameters.
- (void)parseURL:(NSURL *)url
    replyHandler:(void (^)(id parameters, NSError *error))reply;

/// Compose a URL from FSServerURLParameters.
- (void)composeURL:(id)parameters
      replyHandler:(void (^)(NSURL *url, NSError *error))reply;

/// Close a session (no-op is fine for read-only jirafs).
- (void)closeSession:(id)session
        replyHandler:(void (^)(NSError *error))reply;

@end

@implementation JiraFileSystem (ServerURL)

- (id)startOpeningSessionWithTask:(FSTask *)task
                              url:(NSURL *)url
                          options:(NSDictionary *)options
                            error:(NSError **)error
{
    // Allocate an FSServerSessionInfoTask and complete immediately with no session info.
    // fskitd will accept nil session info for anonymous/unauthenticated connections.
    Class cls = NSClassFromString(@"FSServerSessionInfoTask");
    FSServerSessionInfoTask *sessionTask = (FSServerSessionInfoTask *)[[cls alloc] init];
    if (sessionTask) {
        [sessionTask didCompleteWithServerSessionInfo:nil];
    }
    return sessionTask;
}

- (id)startServerInfoFetchWithTask:(FSTask *)task
                               url:(NSURL *)url
                           options:(NSDictionary *)options
                             error:(NSError **)error
{
    // Allocate an FSServerInfoTask and complete with minimal server info.
    Class cls = NSClassFromString(@"FSServerInfoTask");
    FSServerInfoTask *infoTask = (FSServerInfoTask *)[[cls alloc] init];
    if (infoTask) {
        [infoTask didCompleteWithServerInfo:nil];
    }
    return infoTask;
}

- (void)parseURL:(NSURL *)url
    replyHandler:(void (^)(id parameters, NSError *error))reply
{
    // Decompose jira://host[:port][/path] into FSServerURLParameters.
    Class cls = NSClassFromString(@"FSServerURLParameters");
    id params = [[cls alloc] init];
    if (params) {
        [params setValue:url.scheme    forKey:@"scheme"];
        [params setValue:url.host      forKey:@"host"];
        if (url.port) {
            [params setValue:url.port  forKey:@"port"];
        }
        [params setValue:url.path ?: @"" forKey:@"path"];
    }
    reply(params, nil);
}

- (void)composeURL:(id)parameters
      replyHandler:(void (^)(NSURL *url, NSError *error))reply
{
    // Reconstruct a URL from FSServerURLParameters.
    NSString *scheme = [parameters valueForKey:@"scheme"] ?: @"jira";
    NSString *host   = [parameters valueForKey:@"host"]   ?: @"";
    NSNumber *port   = [parameters valueForKey:@"port"];
    NSString *path   = [parameters valueForKey:@"path"]   ?: @"";

    NSURLComponents *components = [[NSURLComponents alloc] init];
    components.scheme = scheme;
    components.host   = host;
    components.port   = port;
    components.path   = path;
    reply(components.URL, nil);
}

- (void)closeSession:(id)session
        replyHandler:(void (^)(NSError *error))reply
{
    // jirafs is stateless/read-only; nothing to tear down.
    reply(nil);
}

@end

// ---------------------------------------------------------------------------
// Register FSServerURLUnaryOperations conformance at load time.
// ---------------------------------------------------------------------------
// JiraFileSystem does NOT declare FSServerURLUnaryOperations as a static Swift
// conformance (doing so from Swift would require a circular bridging-header
// import).  Instead, class_addProtocol runs at dylib-load time so that
// fskitd's -conformsToProtocol: check succeeds.  The five protocol methods are
// already present on JiraFileSystem via the (ServerURL) category above.

__attribute__((constructor))
static void registerServerURLConformance(void) {
    Protocol *proto = objc_getProtocol("FSServerURLUnaryOperations");
    Class cls = NSClassFromString(@"JiraFileSystem");
    if (proto && cls) {
        class_addProtocol(cls, proto);
    }
}
