name: Release drafter
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  draft_release:
    runs-on: ubuntu-latest
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
      # for release workflow
      id-token: write
      attestations: write
    outputs:
      tag_name: ${{ steps.release-drafter.outputs.tag_name }}
    steps:
      - uses: release-drafter/release-drafter@5de93583980a40bd78603b6dfdcda5b4df377b32 # v7.2.0
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_release:
    needs: draft_release
    uses: ./.github/workflows/release.yml
    if: github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
      id-token: write
      attestations: write
    with:
      publish: true
      ref: ${{ needs.draft_release.outputs.tag_name }}
